name: synthenv
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - boost=1.74.0
  - boost-cpp=1.74.0
  - bzip2=1.0.8
  - ca-certificates=2021.5.30
  - cairo=1.16.0
  - certifi=2021.5.30
  - cudatoolkit=11.1.74
  - cycler=0.10.0
  - fontconfig=2.13.1
  - freetype=2.10.4
  - gettext=0.19.8.1
  - greenlet=1.1.0
  - icu=68.1
  - intel-openmp
  - jbig=2.1
  - jpeg=9d
  - kiwisolver=1.3.1
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=2.2.1
  - libdeflate=1.7
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libglib=2.68.3
  - libgomp=9.3.0
  - libiconv=1.16
  - libopenblas=0.3.15
  - libpng=1.6.37
  - libstdcxx-ng=9.3.0
  - libtiff=4.3.0
  - libuuid=2.32.1
  # - libuv=1.40.0
  - libwebp-base=1.2.0
  - libxcb=1.13
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - matplotlib-base=3.4.2
  - mkl=2021.3.0
  - mkl-service=2.4.0
  # - mkl_fft=1.3.0
  # - mkl_random=1.2.2
  - ncurses=6.2
  - ninja=1.10.2
  - numpy=1.20.3
  # - numpy-base=1.20.3
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1k
  - pandas=1.3.0
  - pcre=8.45
  - pillow=8.3.1
  - pip=21.1.3
  - pixman=0.40.0
  - pthread-stubs=0.4
  - pycairo=1.20.1
  - pyparsing=2.4.7
  - python=3.9.6
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytorch=1.9.0
  - pytz=2021.1
  - rdkit=2021.03.4
  - readline=8.1
  - reportlab=3.5.68
  - setuptools=49.6.0
  - six=1.16.0
  - sqlalchemy=1.4.21
  - sqlite=3.36.0
  - tk=8.6.10
  - torchaudio=0.9.0
  - torchvision=0.2.2
  - tornado=6.1
  - typing_extensions=3.10.0.0
  - tzdata=2021a
  - wheel=0.36.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - absl-py==0.13.0
    - aiohttp==3.7.4.post0
    - anyio==3.3.0
    - argon2-cffi==20.1.0
    - async-generator==1.10
    - async-timeout==3.0.1
    - attrs==21.2.0
    - babel==2.9.1
    - backcall==0.2.0
    - bleach==4.0.0
    - cachetools==4.2.2
    - cffi==1.14.6
    - chardet==4.0.0
    - charset-normalizer==2.0.3
    - cloudpickle==1.6.0
    - debugpy==1.4.1
    - decorator==4.4.2
    - defusedxml==0.7.1
    - dgl-cu110==0.6.1
    - dgllife==0.2.8
    - dill==0.3.4
    - entrypoints==0.3
    - fsspec==2021.7.0
    - future==0.18.2
    - fuzzywuzzy==0.18.0
    - google-auth==1.33.1
    - google-auth-oauthlib==0.4.4
    - grpcio==1.38.1
    - hyperopt==0.2.5
    - idna==3.2
    - ipdb==0.13.9
    - ipykernel==6.1.0
    - ipython==7.25.0
    - ipython-genutils==0.2.0
    - jedi==0.18.0
    - jinja2==3.0.1
    - joblib==1.0.1
    - json5==0.9.6
    - jsonschema==3.2.0
    - jupyter-client==6.1.12
    - jupyter-core==4.7.1
    - jupyter-server==1.10.2
    - jupyterlab==3.1.6
    - jupyterlab-pygments==0.1.2
    - jupyterlab-server==2.7.0
    - markdown==3.3.4
    - markupsafe==2.0.1
    - matplotlib-inline==0.1.2
    - mistune==0.8.4
    - multidict==5.1.0
    - nbclassic==0.3.1
    - nbclient==0.5.3
    - nbconvert==6.1.0
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - networkx==2.5.1
    - notebook==6.4.3
    - oauthlib==3.1.1
    - packaging==21.0
    - pandocfilters==1.4.3
    - parso==0.8.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prometheus-client==0.11.0
    - prompt-toolkit==3.0.19
    - protobuf==3.17.3
    - ptyprocess==0.7.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pydeprecate==0.3.0
    - pygments==2.9.0
    - pyrsistent==0.18.0
    - pytdc==0.2.0
    - pytorch-lightning==1.3.8
    - pyyaml==5.4.1
    - pyzmq==22.2.1
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - requests-unixsocket==0.2.0
    - rsa==4.7.2
    - scikit-learn==0.24.2
    - scipy==1.7.0
    - seaborn==0.11.1
    - send2trash==1.8.0
    - shutup==0.1.1
    - sniffio==1.2.0
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.8.0
    - terminado==0.11.0
    - testpath==0.5.0
    - threadpoolctl==2.2.0
    - toml==0.10.2
    - torchmetrics==0.4.1
    - tqdm==4.61.2
    - traitlets==5.0.5
    - urllib3==1.26.6
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.2.0
    - werkzeug==2.0.1
    - yarl==1.6.3
